# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20180626_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='desr',
            new_name='descr',
        ),
    ]
